name: "Install LibEQOL release"
description: "Fetch the latest LibEQOL release ZIP and extract it into a target directory."

inputs:
  destination:
    description: "Directory where LibEQOL should be extracted (e.g. EnhanceQoL/libs)."
    required: true
  repo:
    description: "Repository to pull the release from."
    required: false
    default: "R41z0r/LibEQOL"
  github-token:
    description: "GitHub token for API calls (defaults to github.token)."
    required: false

outputs:
  tag:
    description: "Latest release tag."
    value: ${{ steps.release.outputs.tag }}
  asset_url:
    description: "Download URL of the release asset."
    value: ${{ steps.release.outputs.asset_url }}

runs:
  using: "composite"
  steps:
    - id: release
      name: Resolve latest release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token || github.token }}
        REPO: ${{ inputs.repo }}
      run: |
        set -euo pipefail

        if ! command -v jq >/dev/null 2>&1; then
          echo "jq is required to parse GitHub API responses" >&2
          exit 1
        fi

        api="https://api.github.com/repos/${REPO}/releases/latest"
        response=$(curl -sS \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$api")

        tag=$(printf '%s' "$response" | jq -r '.tag_name // empty')
        asset_url=$(printf '%s' "$response" | jq -r '.assets[]? | select(.browser_download_url != null) | .browser_download_url' | head -n 1)

        if [ -z "$tag" ] || [ -z "$asset_url" ]; then
          echo "Failed to resolve release tag or asset URL from ${api}" >&2
          exit 1
        fi

        echo "tag=${tag}" >> "$GITHUB_OUTPUT"
        echo "asset_url=${asset_url}" >> "$GITHUB_OUTPUT"

    - id: download
      name: Download release asset
      shell: bash
      env:
        ASSET_URL: ${{ steps.release.outputs.asset_url }}
        ZIP_PATH: ${{ runner.temp }}/libeqol.zip
      run: |
        set -euo pipefail
        curl -sSL "${ASSET_URL}" -o "${ZIP_PATH}"
        echo "zip_path=${ZIP_PATH}" >> "$GITHUB_OUTPUT"

    - name: Extract release
      shell: bash
      env:
        DESTINATION: ${{ inputs.destination }}
        ZIP_PATH: ${{ steps.download.outputs.zip_path }}
      run: |
        set -euo pipefail
        mkdir -p "${DESTINATION}"
        unzip -o "${ZIP_PATH}" -d "${DESTINATION}"
        rm -f "${ZIP_PATH}"

    - name: Stage LibEQOL
      shell: bash
      env:
        DESTINATION: ${{ inputs.destination }}
        GIT_USER: ${{ env.GIT_AUTHOR_NAME }}
        GIT_EMAIL: ${{ env.GIT_AUTHOR_EMAIL }}
      run: |
        set -euo pipefail
        git config user.name "${GIT_USER:-github-actions[bot]}"
        git config user.email "${GIT_EMAIL:-github-actions[bot]@users.noreply.github.com}"
        git add "${DESTINATION%/}/LibEQOL"
